# This file is generated by scripts/generate-homebrew-cask.ts.
# Do not edit release values manually; CI rewrites the tap cask on every tagged release.

cask "nodex" do
  version "0.1.8"

  on_arm do
    sha256 "f46aa8912f55eb8556dab4e4058af66f7843d499c01e267a88a9d6fbd459a479"

    url "https://github.com/junyudev/nodex/releases/download/v#{version}/Nodex-#{version}-arm64.dmg",
        verified: "github.com/junyudev/nodex/"
  end

  on_intel do
    sha256 "8e3530d3635ffb1cc0fb3629ee1a3050eb47e3b988d16fb0d60929ba7eeb473f"

    url "https://github.com/junyudev/nodex/releases/download/v#{version}/Nodex-#{version}-x64.dmg",
        verified: "github.com/junyudev/nodex/"
  end

  name "Nodex"
  desc "Block-based Agent Orchestrator"
  homepage "https://github.com/junyudev/nodex"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  depends_on macos: ">= :monterey"
  auto_updates true

  app "Nodex.app"

  zap trash: [
    "~/.nodex",
    "~/Library/Application Support/nodex",
    "~/Library/Preferences/app.jyu.nodex.plist",
    "~/Library/Saved Application State/app.jyu.nodex.savedState",
  ]
end
