# This file is generated by scripts/generate-homebrew-cask.ts.
# Do not edit release values manually; CI rewrites the tap cask on every tagged release.

cask "nodex" do
  version "0.1.5"

  on_arm do
    sha256 "be71c167b742fb33423bdc68ca46f698c0807cdb2b4796bcb3d2a388b46edd01"

    url "https://github.com/Asphocarp/nodex/releases/download/v#{version}/Nodex-#{version}-arm64.dmg",
        verified: "github.com/Asphocarp/nodex/"
  end

  on_intel do
    sha256 "ebe59624e40e6ddbcb78ca3e75767e4d230163a350a7f3d9816d1dfad8a65512"

    url "https://github.com/Asphocarp/nodex/releases/download/v#{version}/Nodex-#{version}-x64.dmg",
        verified: "github.com/Asphocarp/nodex/"
  end

  name "Nodex"
  desc "Block-based Agent Orchestrator"
  homepage "https://github.com/Asphocarp/nodex"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  app "Nodex.app"

  zap trash: [
    "~/.nodex",
    "~/Library/Application Support/nodex",
    "~/Library/Preferences/app.jyu.nodex.plist",
    "~/Library/Saved Application State/app.jyu.nodex.savedState",
  ]
end
