# This file is generated by scripts/generate-homebrew-cask.ts.
# Do not edit release values manually; CI rewrites the tap cask on every tagged release.

cask "nodex" do
  version "0.1.7"

  on_arm do
    sha256 "b3831abc9001caf57822bea4c778237c7d4fed439e291aa2073dc2a5aa28f292"

    url "https://github.com/junyudev/nodex/releases/download/v#{version}/Nodex-#{version}-arm64.dmg",
        verified: "github.com/junyudev/nodex/"
  end

  on_intel do
    sha256 "fabf02beb8aa70436dbcbd9f3aaa577c43a148f9fe0667c5c4e18f2aef3ab002"

    url "https://github.com/junyudev/nodex/releases/download/v#{version}/Nodex-#{version}-x64.dmg",
        verified: "github.com/junyudev/nodex/"
  end

  name "Nodex"
  desc "Block-based Agent Orchestrator"
  homepage "https://github.com/junyudev/nodex"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  depends_on macos: ">= :monterey"
  auto_updates true

  app "Nodex.app"

  zap trash: [
    "~/.nodex",
    "~/Library/Application Support/nodex",
    "~/Library/Preferences/app.jyu.nodex.plist",
    "~/Library/Saved Application State/app.jyu.nodex.savedState",
  ]
end
